#!/usr/bin/env bash
# Corpus health check. Exit non-zero on failure so it can gate a commit.
#   bash corpus/lint.sh           check
#   bash corpus/lint.sh --index   regenerate index.md's catalog block
set -uo pipefail
cd "$(dirname "$0")"

MAX_BODY_LINES=200
fail=0
note() { printf '  %s\n' "$*"; }
bad()  { printf '  ✗ %s\n' "$*"; fail=1; }

body_lines() { # strip frontmatter, count the rest
  awk 'NR==1 && $0=="---"{fm=1;next} fm && $0=="---"{fm=0;next} !fm{n++} END{print n+0}' "$1"
}
frontmatter_has() { awk 'NR==1&&$0=="---"{fm=1;next} fm&&$0=="---"{exit} fm' "$1" | grep -q "^$2:"; }

if [ "${1:-}" = "--index" ]; then
  {
    echo "<!-- CATALOG:BEGIN — generated by lint.sh --index, do not hand-edit -->"
    for f in wiki/*.md; do
      s=$(awk 'NR==1&&$0=="---"{fm=1;next} fm&&$0=="---"{exit} fm' "$f" | sed -n 's/^summary: *//p')
      echo "- [\`wiki/$(basename "$f")\`](./$f) — ${s:-<no summary>}"
    done
    echo "<!-- CATALOG:END -->"
  } > /tmp/.corpus-catalog.$$
  if grep -q 'CATALOG:BEGIN' index.md 2>/dev/null; then
    awk -v cat="/tmp/.corpus-catalog.$$" '
      /CATALOG:BEGIN/{while((getline l < cat)>0) print l; skip=1; next}
      /CATALOG:END/{skip=0; next}
      !skip' index.md > index.md.new && mv index.md.new index.md
  else
    cat /tmp/.corpus-catalog.$$ >> index.md
  fi
  rm -f /tmp/.corpus-catalog.$$
  echo "index.md catalog regenerated."
  exit 0
fi

echo "corpus lint"
echo "── frontmatter ──"
for f in wiki/*.md routing.md; do
  [ -e "$f" ] || continue
  frontmatter_has "$f" summary || bad "$f: missing 'summary:'"
  frontmatter_has "$f" updated || bad "$f: missing 'updated:'"
done

echo "── page size (max $MAX_BODY_LINES body lines) ──"
for f in wiki/*.md; do
  n=$(body_lines "$f")
  [ "$n" -gt "$MAX_BODY_LINES" ] && bad "$f: $n body lines — split it"
done

echo "── relative links resolve ──"
# NB: process substitution, not a pipe — `bad` must run in this shell or its
# failure flag is lost to the subshell and the lint reports clean while failing.
for f in $(find . -name '*.md' -not -path './node_modules/*'); do
  while IFS= read -r l; do
    [ -e "$(dirname "$f")/$l" ] || bad "$f: broken link → $l"
  done < <(grep -oE '\]\(\.[^)#]*\)' "$f" 2>/dev/null | sed -E 's/^\]\(//; s/\)$//')
done

echo "── brief numbers unique ──"
dups=$(ls briefs/todo briefs/done briefs/superseded 2>/dev/null \
       | grep -oE '^[0-9]+' | sort | uniq -d)
[ -n "$dups" ] && bad "duplicate brief numbers: $dups"

echo "── abandoned path roots referenced ──"
for p in packages scenes apps; do
  if grep -rqE "\`$p/" wiki/ 2>/dev/null && [ ! -d "../$p" ]; then
    note "wiki references \`$p/\` which does not exist yet (fine if planned)"
  fi
done

if [ "$fail" -eq 0 ]; then echo "✓ corpus clean"; else echo "✗ corpus has findings"; fi
exit $fail
