#!/usr/bin/env bash
# The assets `download.sh` skips for size. Generated — re-run `npm run assets`.
# These are decimation *sources*, not things to commit: see DOWNLOADS.md.
set -euo pipefail
cd "$(dirname "$0")"

echo "→ polyhaven/fir_tree_01  (486.6 MB)"
mkdir -p "polyhaven/fir_tree_01"
[ -f "polyhaven/fir_tree_01/fir_tree_01_2k.gltf" ] || curl -fsSL -o "polyhaven/fir_tree_01/fir_tree_01_2k.gltf" "https://dl.polyhaven.org/file/ph-assets/Models/gltf/2k/fir_tree_01/fir_tree_01_2k.gltf"
mkdir -p "polyhaven/fir_tree_01/textures"
[ -f "polyhaven/fir_tree_01/textures/fir_tree_01_bark_nor_gl_2k.jpg" ] || curl -fsSL -o "polyhaven/fir_tree_01/textures/fir_tree_01_bark_nor_gl_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/fir_tree_01/fir_tree_01_bark_nor_gl_2k.jpg"
mkdir -p "polyhaven/fir_tree_01/textures"
[ -f "polyhaven/fir_tree_01/textures/fir_tree_01_bark_diff_2k.jpg" ] || curl -fsSL -o "polyhaven/fir_tree_01/textures/fir_tree_01_bark_diff_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/fir_tree_01/fir_tree_01_bark_diff_2k.jpg"
mkdir -p "polyhaven/fir_tree_01/textures"
[ -f "polyhaven/fir_tree_01/textures/fir_tree_01_bark_arm_2k.jpg" ] || curl -fsSL -o "polyhaven/fir_tree_01/textures/fir_tree_01_bark_arm_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/fir_tree_01/fir_tree_01_bark_arm_2k.jpg"
mkdir -p "polyhaven/fir_tree_01/textures"
[ -f "polyhaven/fir_tree_01/textures/fir_tree_01_trunk_a_nor_gl_2k.jpg" ] || curl -fsSL -o "polyhaven/fir_tree_01/textures/fir_tree_01_trunk_a_nor_gl_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/fir_tree_01/fir_tree_01_trunk_a_nor_gl_2k.jpg"
mkdir -p "polyhaven/fir_tree_01/textures"
[ -f "polyhaven/fir_tree_01/textures/fir_tree_01_trunk_a_diff_2k.jpg" ] || curl -fsSL -o "polyhaven/fir_tree_01/textures/fir_tree_01_trunk_a_diff_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/fir_tree_01/fir_tree_01_trunk_a_diff_2k.jpg"
mkdir -p "polyhaven/fir_tree_01/textures"
[ -f "polyhaven/fir_tree_01/textures/fir_tree_01_trunk_a_arm_2k.jpg" ] || curl -fsSL -o "polyhaven/fir_tree_01/textures/fir_tree_01_trunk_a_arm_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/fir_tree_01/fir_tree_01_trunk_a_arm_2k.jpg"
mkdir -p "polyhaven/fir_tree_01/textures"
[ -f "polyhaven/fir_tree_01/textures/fir_tree_01_twig_nor_gl_2k.jpg" ] || curl -fsSL -o "polyhaven/fir_tree_01/textures/fir_tree_01_twig_nor_gl_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/fir_tree_01/fir_tree_01_twig_nor_gl_2k.jpg"
mkdir -p "polyhaven/fir_tree_01/textures"
[ -f "polyhaven/fir_tree_01/textures/fir_tree_01_twig_diff_2k.jpg" ] || curl -fsSL -o "polyhaven/fir_tree_01/textures/fir_tree_01_twig_diff_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/fir_tree_01/fir_tree_01_twig_diff_2k.jpg"
mkdir -p "polyhaven/fir_tree_01/textures"
[ -f "polyhaven/fir_tree_01/textures/fir_tree_01_twig_arm_2k.jpg" ] || curl -fsSL -o "polyhaven/fir_tree_01/textures/fir_tree_01_twig_arm_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/fir_tree_01/fir_tree_01_twig_arm_2k.jpg"
mkdir -p "polyhaven/fir_tree_01/textures"
[ -f "polyhaven/fir_tree_01/textures/fir_tree_01_trunk_b_nor_gl_2k.jpg" ] || curl -fsSL -o "polyhaven/fir_tree_01/textures/fir_tree_01_trunk_b_nor_gl_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/fir_tree_01/fir_tree_01_trunk_b_nor_gl_2k.jpg"
mkdir -p "polyhaven/fir_tree_01/textures"
[ -f "polyhaven/fir_tree_01/textures/fir_tree_01_trunk_b_diff_2k.jpg" ] || curl -fsSL -o "polyhaven/fir_tree_01/textures/fir_tree_01_trunk_b_diff_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/fir_tree_01/fir_tree_01_trunk_b_diff_2k.jpg"
mkdir -p "polyhaven/fir_tree_01/textures"
[ -f "polyhaven/fir_tree_01/textures/fir_tree_01_trunk_b_arm_2k.jpg" ] || curl -fsSL -o "polyhaven/fir_tree_01/textures/fir_tree_01_trunk_b_arm_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/fir_tree_01/fir_tree_01_trunk_b_arm_2k.jpg"
[ -f "polyhaven/fir_tree_01/fir_tree_01.bin" ] || curl -fsSL -o "polyhaven/fir_tree_01/fir_tree_01.bin" "https://dl.polyhaven.org/file/ph-assets/Models/gltf/8k/fir_tree_01/fir_tree_01.bin"

echo "→ polyhaven/pine_tree_01  (936.7 MB)"
mkdir -p "polyhaven/pine_tree_01"
[ -f "polyhaven/pine_tree_01/pine_tree_01_2k.gltf" ] || curl -fsSL -o "polyhaven/pine_tree_01/pine_tree_01_2k.gltf" "https://dl.polyhaven.org/file/ph-assets/Models/gltf/2k/pine_tree_01/pine_tree_01_2k.gltf"
mkdir -p "polyhaven/pine_tree_01/textures"
[ -f "polyhaven/pine_tree_01/textures/pine_tree_01_bark_nor_gl_2k.jpg" ] || curl -fsSL -o "polyhaven/pine_tree_01/textures/pine_tree_01_bark_nor_gl_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/pine_tree_01/pine_tree_01_bark_nor_gl_2k.jpg"
mkdir -p "polyhaven/pine_tree_01/textures"
[ -f "polyhaven/pine_tree_01/textures/pine_tree_01_bark_diff_2k.jpg" ] || curl -fsSL -o "polyhaven/pine_tree_01/textures/pine_tree_01_bark_diff_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/pine_tree_01/pine_tree_01_bark_diff_2k.jpg"
mkdir -p "polyhaven/pine_tree_01/textures"
[ -f "polyhaven/pine_tree_01/textures/pine_tree_01_bark_arm_2k.jpg" ] || curl -fsSL -o "polyhaven/pine_tree_01/textures/pine_tree_01_bark_arm_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/pine_tree_01/pine_tree_01_bark_arm_2k.jpg"
mkdir -p "polyhaven/pine_tree_01/textures"
[ -f "polyhaven/pine_tree_01/textures/pine_tree_01_trunk_a_nor_gl_2k.jpg" ] || curl -fsSL -o "polyhaven/pine_tree_01/textures/pine_tree_01_trunk_a_nor_gl_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/pine_tree_01/pine_tree_01_trunk_a_nor_gl_2k.jpg"
mkdir -p "polyhaven/pine_tree_01/textures"
[ -f "polyhaven/pine_tree_01/textures/pine_tree_01_trunk_a_diff_2k.jpg" ] || curl -fsSL -o "polyhaven/pine_tree_01/textures/pine_tree_01_trunk_a_diff_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/pine_tree_01/pine_tree_01_trunk_a_diff_2k.jpg"
mkdir -p "polyhaven/pine_tree_01/textures"
[ -f "polyhaven/pine_tree_01/textures/pine_tree_01_trunk_a_arm_2k.jpg" ] || curl -fsSL -o "polyhaven/pine_tree_01/textures/pine_tree_01_trunk_a_arm_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/pine_tree_01/pine_tree_01_trunk_a_arm_2k.jpg"
mkdir -p "polyhaven/pine_tree_01/textures"
[ -f "polyhaven/pine_tree_01/textures/pine_tree_01_twig_nor_gl_2k.jpg" ] || curl -fsSL -o "polyhaven/pine_tree_01/textures/pine_tree_01_twig_nor_gl_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/pine_tree_01/pine_tree_01_twig_nor_gl_2k.jpg"
mkdir -p "polyhaven/pine_tree_01/textures"
[ -f "polyhaven/pine_tree_01/textures/pine_tree_01_twig_diff_2k.jpg" ] || curl -fsSL -o "polyhaven/pine_tree_01/textures/pine_tree_01_twig_diff_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/pine_tree_01/pine_tree_01_twig_diff_2k.jpg"
mkdir -p "polyhaven/pine_tree_01/textures"
[ -f "polyhaven/pine_tree_01/textures/pine_tree_01_twig_arm_2k.jpg" ] || curl -fsSL -o "polyhaven/pine_tree_01/textures/pine_tree_01_twig_arm_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/pine_tree_01/pine_tree_01_twig_arm_2k.jpg"
mkdir -p "polyhaven/pine_tree_01/textures"
[ -f "polyhaven/pine_tree_01/textures/pine_tree_01_trunk_b_nor_gl_2k.jpg" ] || curl -fsSL -o "polyhaven/pine_tree_01/textures/pine_tree_01_trunk_b_nor_gl_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/pine_tree_01/pine_tree_01_trunk_b_nor_gl_2k.jpg"
mkdir -p "polyhaven/pine_tree_01/textures"
[ -f "polyhaven/pine_tree_01/textures/pine_tree_01_trunk_b_diff_2k.jpg" ] || curl -fsSL -o "polyhaven/pine_tree_01/textures/pine_tree_01_trunk_b_diff_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/pine_tree_01/pine_tree_01_trunk_b_diff_2k.jpg"
mkdir -p "polyhaven/pine_tree_01/textures"
[ -f "polyhaven/pine_tree_01/textures/pine_tree_01_trunk_b_arm_2k.jpg" ] || curl -fsSL -o "polyhaven/pine_tree_01/textures/pine_tree_01_trunk_b_arm_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/pine_tree_01/pine_tree_01_trunk_b_arm_2k.jpg"
[ -f "polyhaven/pine_tree_01/pine_tree_01.bin" ] || curl -fsSL -o "polyhaven/pine_tree_01/pine_tree_01.bin" "https://dl.polyhaven.org/file/ph-assets/Models/gltf/8k/pine_tree_01/pine_tree_01.bin"

echo "→ polyhaven/tree_small_02  (110.0 MB)"
mkdir -p "polyhaven/tree_small_02"
[ -f "polyhaven/tree_small_02/tree_small_02_2k.gltf" ] || curl -fsSL -o "polyhaven/tree_small_02/tree_small_02_2k.gltf" "https://dl.polyhaven.org/file/ph-assets/Models/gltf/2k/tree_small_02/tree_small_02_2k.gltf"
mkdir -p "polyhaven/tree_small_02/textures"
[ -f "polyhaven/tree_small_02/textures/tree_small_02_branch_nor_gl_2k.jpg" ] || curl -fsSL -o "polyhaven/tree_small_02/textures/tree_small_02_branch_nor_gl_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/tree_small_02/tree_small_02_branch_nor_gl_2k.jpg"
mkdir -p "polyhaven/tree_small_02/textures"
[ -f "polyhaven/tree_small_02/textures/tree_small_02_branch_diff_2k.jpg" ] || curl -fsSL -o "polyhaven/tree_small_02/textures/tree_small_02_branch_diff_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/tree_small_02/tree_small_02_branch_diff_2k.jpg"
mkdir -p "polyhaven/tree_small_02/textures"
[ -f "polyhaven/tree_small_02/textures/tree_small_02_branch_arm_2k.jpg" ] || curl -fsSL -o "polyhaven/tree_small_02/textures/tree_small_02_branch_arm_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/tree_small_02/tree_small_02_branch_arm_2k.jpg"
mkdir -p "polyhaven/tree_small_02/textures"
[ -f "polyhaven/tree_small_02/textures/tree_small_02_leaves_nor_gl_2k.jpg" ] || curl -fsSL -o "polyhaven/tree_small_02/textures/tree_small_02_leaves_nor_gl_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/tree_small_02/tree_small_02_leaves_nor_gl_2k.jpg"
mkdir -p "polyhaven/tree_small_02/textures"
[ -f "polyhaven/tree_small_02/textures/tree_small_02_leaves_diff_2k.jpg" ] || curl -fsSL -o "polyhaven/tree_small_02/textures/tree_small_02_leaves_diff_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/tree_small_02/tree_small_02_leaves_diff_2k.jpg"
mkdir -p "polyhaven/tree_small_02/textures"
[ -f "polyhaven/tree_small_02/textures/tree_small_02_leaves_arm_2k.jpg" ] || curl -fsSL -o "polyhaven/tree_small_02/textures/tree_small_02_leaves_arm_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/tree_small_02/tree_small_02_leaves_arm_2k.jpg"
mkdir -p "polyhaven/tree_small_02/textures"
[ -f "polyhaven/tree_small_02/textures/tree_small_02_nor_gl_2k.jpg" ] || curl -fsSL -o "polyhaven/tree_small_02/textures/tree_small_02_nor_gl_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/tree_small_02/tree_small_02_nor_gl_2k.jpg"
mkdir -p "polyhaven/tree_small_02/textures"
[ -f "polyhaven/tree_small_02/textures/tree_small_02_diff_2k.jpg" ] || curl -fsSL -o "polyhaven/tree_small_02/textures/tree_small_02_diff_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/tree_small_02/tree_small_02_diff_2k.jpg"
mkdir -p "polyhaven/tree_small_02/textures"
[ -f "polyhaven/tree_small_02/textures/tree_small_02_arm_2k.jpg" ] || curl -fsSL -o "polyhaven/tree_small_02/textures/tree_small_02_arm_2k.jpg" "https://dl.polyhaven.org/file/ph-assets/Models/jpg/2k/tree_small_02/tree_small_02_arm_2k.jpg"
[ -f "polyhaven/tree_small_02/tree_small_02.bin" ] || curl -fsSL -o "polyhaven/tree_small_02/tree_small_02.bin" "https://dl.polyhaven.org/file/ph-assets/Models/gltf/8k/tree_small_02/tree_small_02.bin"

