/**
 * The text of `download.sh` and `download-heavy.sh`, assembled from what
 * `download-list.ts` resolved.
 *
 * Separate from the generator so it can be tested without the network — and it
 * needs testing, because everything interpolated here ends up executed by
 * `bash`. Slugs come from scene documents, which are AI-authored, and URLs and
 * filenames come from third-party APIs. A slug carrying a newline used to end a
 * `# UNRESOLVED` comment early and turn the rest of itself into a command.
 *
 * So nothing is interpolated raw: arguments go through `shellQuote`, and text
 * in a comment goes through `shellComment`. The schema constrains `slug` as
 * well, but this file is run by `node` straight against `.scene.json` files on
 * disk, and the sink should not have to trust the layer above it.
 */

export interface Download {
  url: string;
  /** Path under `assets-src/<source>/<slug>/`. */
  target: string;
  bytes: number;
}

export interface ScriptAsset {
  source: string;
  slug: string;
  downloads: Download[];
  note?: string;
}

/** One argument, single-quoted, so no character in it means anything to `bash`. */
export const shellQuote = (value: string): string => `'${value.replaceAll("'", `'\\''`)}'`;

/**
 * Text that has to stay inside a `#` comment. Only a line break can end one,
 * so every control character is flattened to a visible `?`.
 */
export const shellComment = (value: string): string => value.replace(/\p{Cc}/gu, "?");

/**
 * The one download helper both scripts use.
 *
 * Three things, and each earns its place:
 *
 * 1. **`.part`, then `mv`.** `curl -fsSL -o "$target"` writes in place, and the
 *    only check was `[ -f "$target" ]` — so a transfer cut off mid-stream left
 *    a truncated `.gltf` on disk, and because the file now *existed*, every
 *    future run skipped it **forever**. The scene then loaded broken geometry
 *    with nothing surfacing an error: `assets/manifest.ts` checks a file is
 *    present, never that it is valid. This project has already shipped a 404
 *    page saved as a model once.
 *
 *    `curl -f` does not cover this: it guards against an HTTP error *response*,
 *    not against a connection dropping mid-body.
 *
 * 2. **Size check where the source reports one.** Poly Haven and ambientCG both
 *    do. A file that arrives the wrong length is deleted rather than kept, so
 *    the next run retries instead of inheriting the corruption.
 *
 * 3. **A plausibility floor for what is already there.** A `.gltf` of 300 bytes
 *    or a `.jpg` of 1 KB is the shape of an error page, and an existing file is
 *    otherwise never looked at again.
 */
export const HELPERS = String.raw`
fetch_one() {                                 # url target expected_bytes
  local url="$1" target="$2" want="$3" got

  if [ -f "$target" ]; then
    got=$(wc -c < "$target")
    if [ "$want" -gt 0 ] && [ "$got" -ne "$want" ]; then
      echo "  ! $target is $got bytes, expected $want — refetching" >&2
      rm -f "$target"
    elif [ "$got" -lt 512 ]; then
      echo "  ! $target is only $got bytes — suspiciously small, refetching" >&2
      rm -f "$target"
    else
      return 0
    fi
  fi

  # Never onto the target itself: an interrupted transfer must not leave
  # something the existence check above will accept for the rest of time.
  curl -fsSL -o "$target.part" "$url"
  got=$(wc -c < "$target.part")
  if [ "$want" -gt 0 ] && [ "$got" -ne "$want" ]; then
    rm -f "$target.part"
    echo "  ✗ $target: got $got bytes, expected $want" >&2
    return 1
  fi
  mv "$target.part" "$target"
}
`;

const header = (lines: string[]): string[] => [
  "#!/usr/bin/env bash",
  ...lines,
  "set -euo pipefail",
  'cd "$(dirname "$0")"',
  HELPERS,
  "",
];

/** `mkdir` and `fetch_one` for every file of one asset. */
const fetchLines = (dir: string, d: Download): string[] => {
  const target = `${dir}/${d.target}`;
  const lines: string[] = [];
  if (d.target.includes("/"))
    lines.push(`mkdir -p ${shellQuote(`${dir}/${d.target.replace(/\/[^/]+$/, "")}`)}`);
  lines.push(`fetch_one ${shellQuote(d.url)} ${shellQuote(target)} ${Math.trunc(d.bytes)}`);
  return lines;
};

export function downloadScript(
  fetchable: ScriptAsset[],
  missing: ScriptAsset[],
  heavy: ScriptAsset[],
  size: (a: ScriptAsset) => string,
): string {
  return [
    ...header(["# Generated by `node assets/download-list.ts`. Re-run that, not this, to update."]),
    ...fetchable.flatMap((r) => {
      const dir = `${r.source}/${r.slug}`;
      const lines = [`echo ${shellQuote(`→ ${dir}`)}`, `mkdir -p ${shellQuote(dir)}`];
      for (const d of r.downloads) {
        lines.push(...fetchLines(dir, d));
        if (d.target.endsWith(".zip")) {
          const target = `${dir}/${d.target}`;
          lines.push(`unzip -oq ${shellQuote(target)} -d ${shellQuote(dir)} && rm ${shellQuote(target)}`);
          // ambientCG ships a whole DCC bundle in every zip. Keep the maps a
          // renderer can use and drop the rest: `.blend`/`.usdc`/`.mtlx`/`.tres`
          // are for other tools, the bare `.png` is a catalogue thumbnail, and
          // `NormalDX` is the DirectX-convention normal map — three.js wants the
          // OpenGL one, and carrying both doubles the largest file in the set.
          lines.push(
            `find ${shellQuote(dir)} -type f \\( -name '*.blend' -o -name '*.usdc' -o -name '*.mtlx' -o -name '*.tres' -o -name '*NormalDX*' -o -name ${shellQuote(`${r.slug}.png`)} \\) -delete`,
          );
        }
      }
      return [...lines, ""];
    }),
    ...missing.map((m) => `# UNRESOLVED ${shellComment(`${m.source}/${m.slug} — ${m.note ?? ""}`)}`),
    ...heavy.map(
      (h) => `# SKIPPED ${shellComment(`${h.source}/${h.slug} — ${size(h)}`)}, see download-heavy.sh`,
    ),
    'echo "done — now run: npm run check"',
    "",
  ].join("\n");
}

export function heavyScript(heavy: ScriptAsset[], size: (a: ScriptAsset) => string): string {
  return [
    ...header([
      "# The assets `download.sh` skips for size. Generated — re-run `npm run assets`.",
      "# These are decimation *sources*, not things to commit: see DOWNLOADS.md.",
    ]),
    ...heavy.flatMap((r) => {
      const dir = `${r.source}/${r.slug}`;
      const lines = [`echo ${shellQuote(`→ ${dir}  (${size(r)})`)}`, `mkdir -p ${shellQuote(dir)}`];
      for (const d of r.downloads) lines.push(...fetchLines(dir, d));
      return [...lines, ""];
    }),
    "",
  ].join("\n");
}
