/**
 * The asset manifest: what is actually on disk under `assets-src/`.
 *
 * Generated by scanning, never hand-maintained. A hand-written manifest is a
 * second copy of what the filesystem already says, and it drifts the first time
 * a download is moved — the same reasoning that makes the SQLite scene index a
 * derived thing rather than a source of truth.
 *
 * An asset id is `<source>/<slug>`, which is exactly the directory layout:
 * `assets-src/polyhaven/pine_tree_01/`.
 */
import { readdir, stat } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export const ASSETS_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "assets-src");

/** Sources whose directories are scanned. A directory outside these is ignored. */
export const SOURCES = ["polyhaven", "ambientcg", "cgbookcase", "local"] as const;
export type Source = (typeof SOURCES)[number];

export interface ManifestEntry {
  /** `polyhaven/pine_tree_01` — what a scene document references. */
  id: string;
  source: Source;
  slug: string;
  /** Entry file for a model, relative to the asset directory. Absent for materials. */
  gltf?: string;
  /** A baked angle atlas, when `impostor/atlas.png` is present. */
  impostor?: { atlas: string; meta: string };
  /** Every file found, relative to the asset directory. */
  files: string[];
}

const exists = async (path: string): Promise<boolean> => {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
};

async function walk(dir: string, base = ""): Promise<string[]> {
  const out: string[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const rel = base === "" ? entry.name : `${base}/${entry.name}`;
    if (entry.isDirectory()) out.push(...(await walk(join(dir, entry.name), rel)));
    else out.push(rel);
  }
  return out;
}

/**
 * Scan `assets-src/` and return one entry per asset directory.
 *
 * Returns an empty manifest when the directory does not exist rather than
 * throwing: nothing has been downloaded yet is a legitimate state, and the
 * project has to build in it. What must *not* be legitimate is a scene naming an
 * asset the manifest does not have — that is `asset-resolves`' job, and it only
 * has teeth once this is wired into the build.
 */
export async function readManifest(dir = ASSETS_DIR): Promise<ManifestEntry[]> {
  if (!(await exists(dir))) return [];

  const out: ManifestEntry[] = [];
  for (const source of SOURCES) {
    const sourceDir = join(dir, source);
    if (!(await exists(sourceDir))) continue;

    for (const entry of await readdir(sourceDir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const files = await walk(join(sourceDir, entry.name));
      if (files.length === 0) continue;

      const gltf = files.find((f) => f.endsWith(".gltf") || f.endsWith(".glb"));
      const atlas = files.find((f) => f === "impostor/atlas.png");
      out.push({
        id: `${source}/${entry.name}`,
        source,
        slug: entry.name,
        ...(gltf === undefined ? {} : { gltf }),
        ...(atlas === undefined
          ? {}
          : { impostor: { atlas, meta: "impostor/impostor.json" } }),
        files: files.sort(),
      });
    }
  }
  return out.sort((a, b) => a.id.localeCompare(b.id));
}

/** Just the ids, which is what the linter wants. */
export async function knownAssets(dir = ASSETS_DIR): Promise<Set<string>> {
  return new Set((await readManifest(dir)).map((e) => e.id));
}
